"""
Regenerate tools/stock_lists.py from NSE's published index constituent CSVs.

Usage (from repo root):
    python tools/refresh_stock_lists.py

Downloads ind_nifty{50,100,200,500}list.csv from archives.nseindia.com,
validates counts and subset relationships, and rewrites tools/stock_lists.py.
Run whenever NSE rebalances its indices (typically March / September),
then commit the regenerated file and rerun the EOD backfill so new
constituents get price history.
"""
import csv
import io
import sys
from datetime import date
from pathlib import Path

import httpx

BASE = "https://archives.nseindia.com/content/indices"
INDICES = [
    ("NIFTY50", "NIFTY_50", "ind_nifty50list.csv", 50),
    ("NIFTY100", "NIFTY_100", "ind_nifty100list.csv", 100),
    ("NIFTY200", "NIFTY_200", "ind_nifty200list.csv", 200),
    ("NIFTY500", "NIFTY_500", "ind_nifty500list.csv", 500),
]
HEADERS = {"User-Agent": "Mozilla/5.0"}
OUT = Path(__file__).parent / "stock_lists.py"


def fetch(filename: str) -> list[tuple[str, str]]:
    resp = httpx.get(f"{BASE}/{filename}", headers=HEADERS, timeout=30,
                     follow_redirects=True)
    resp.raise_for_status()
    rows = csv.DictReader(io.StringIO(resp.text))
    out = []
    for r in rows:
        symbol = (r.get("Symbol") or "").strip()
        name = (r.get("Company Name") or "").strip()
        # NSE inserts DUMMY* placeholder rows during demergers (e.g. DUMMYVEDL1)
        # for entities that haven't listed yet — they have no tradable data.
        if symbol and name and not symbol.startswith("DUMMY"):
            out.append((f"{symbol}.NS", name))
    return out


def main() -> None:
    lists: dict[str, list[tuple[str, str]]] = {}
    for key, _var, filename, expected in INDICES:
        constituents = fetch(filename)
        # NSE counts drift by a few names mid-rebalance; a big deviation means
        # a malformed download — abort rather than overwrite good data.
        if abs(len(constituents) - expected) > 5:
            sys.exit(f"{key}: got {len(constituents)} constituents, expected "
                     f"~{expected} — aborting, stock_lists.py left untouched")
        lists[key] = constituents
        print(f"{key}: {len(constituents)} constituents")

    n50 = {t for t, _ in lists["NIFTY50"]}
    n500 = {t for t, _ in lists["NIFTY500"]}
    missing = sorted(n50 - n500)
    if missing:
        sys.exit(f"sanity check failed: {missing} in NIFTY50 but not in "
                 "NIFTY500 — aborting, stock_lists.py left untouched")

    body = [
        '"""',
        "NSE index constituent lists (WAT Layer 3 data module).",
        "",
        "Single source of truth for NIFTY50/100/200/500, used by both the FastAPI",
        "backend (/market/scan) and tools/eod_pipeline.py.",
        f"Generated by tools/refresh_stock_lists.py from NSE CSVs on {date.today()}.",
        "Do not edit by hand — rerun the refresh script instead.",
        '"""',
        "",
    ]
    for key, var, _filename, _expected in INDICES:
        body.append(f"{var} = [")
        for ticker, name in lists[key]:
            body.append(f"    ({ticker!r}, {name!r}),")
        body.append("]")
        body.append("")
    body.append("STOCK_LISTS: dict[str, list] = {")
    for key, var, _filename, _expected in INDICES:
        body.append(f"    {key!r}: {var},")
    body.append("}")
    OUT.write_text("\n".join(body) + "\n")
    print(f"Wrote {OUT} ({sum(len(v) for v in lists.values())} entries)")


if __name__ == "__main__":
    main()
